# Generated by Django 2.1.7 on 2019-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='point_one_x',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='point_one_y',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='point_two_x',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='point_two_y',
            new_name='top',
        ),
    ]
