# Generated by Django 2.1.7 on 2019-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='class_img',
            field=models.CharField(default='', max_length=64, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
