# Generated by Django 2.1.7 on 2019-04-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190330_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс изображений',
                'verbose_name_plural': 'Классы изображений',
            },
        ),
        migrations.CreateModel(
            name='ImageToClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'image_to_class',
            },
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='image',
            name='class_img',
        ),
        migrations.AddField(
            model_name='imagetoclass',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
        migrations.AddField(
            model_name='imagetoclass',
            name='image_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ImageClass'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='image_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ImageClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='classes',
            field=models.ManyToManyField(related_name='images', through='core.ImageToClass', to='core.ImageClass', verbose_name='Классы изображения'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetoclass',
            unique_together={('image', 'image_class')},
        ),
    ]
