# Generated by Django 2.1.7 on 2019-04-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190410_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Стиль изображений',
                'verbose_name_plural': 'Стили изображений',
            },
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='style',
        ),
        migrations.AddField(
            model_name='image',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Style'),
        ),
    ]
