# Generated by Django 2.1.7 on 2019-07-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190725_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Техника'),
        ),
    ]
