const constants = {
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",

    LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
    LOGIN_FAILED: "LOGIN_FAILED",

    REGISTRATION_SUCCESSFUL: "REGISTRATION_SUCCESSFUL",
    REGISTRATION_FAILED: "REGISTRATION_FAILED",

    LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
    LOGOUT_FAILED: "LOGOUT_FAILED",

    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",

    SAVE_ANNOTATIONS_REQUEST: "SAVE_ANNOTATIONS_REQUEST",
    SAVE_ANNOTATIONS_SUCCESSFUL: "SAVE_ANNOTATIONS_SUCCESSFUL",
    SAVE_ANNOTATIONS_FAILED: "SAVE_ANNOTATIONS_FAILED",

    LOAD_IMAGE_REQUEST: "LOAD_IMAGE_REQUEST",
    LOAD_IMAGE_SUCCESSFUL: "LOAD_IMAGE_SUCCESSFUL",
    LOAD_IMAGE_FAILED: "LOAD_IMAGE_FAILED",
};

export default constants;
