const constants = {
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",

    LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
    LOGIN_FAILED: "LOGIN_FAILED",

    REGISTRATION_SUCCESSFUL: "REGISTRATION_SUCCESSFUL",
    REGISTRATION_FAILED: "REGISTRATION_FAILED",

    LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
    LOGOUT_FAILED: "LOGOUT_FAILED",

    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",

    SAVE_DETECTIONS_REQUEST: "SAVE_DETECTIONS_REQUEST",
    SAVE_DETECTIONS_SUCCESSFUL: "SAVE_DETECTIONS_SUCCESSFUL",
    SAVE_DETECTIONS_FAILED: "SAVE_DETECTIONS_FAILED",

    SAVE_CLASSIFICATION_REQUEST: "SAVE_CLASSIFICATION_REQUEST",
    SAVE_CLASSIFICATION_SUCCESSFUL: "SAVE_CLASSIFICATION_SUCCESSFUL",
    SAVE_CLASSIFICATION_FAILED: "SAVE_CLASSIFICATION_FAILED",

    LOAD_IMAGE_REQUEST: "LOAD_IMAGE_REQUEST",
    LOAD_IMAGE_SUCCESSFUL: "LOAD_IMAGE_SUCCESSFUL",
    LOAD_IMAGE_FAILED: "LOAD_IMAGE_FAILED",

    DELETE_IMAGE_REQUEST: "DELETE_IMAGE_REQUEST",
    DELETE_IMAGE_SUCCESSFUL: "DELETE_IMAGE_SUCCESSFUL",
    DELETE_IMAGE_FAILED: "DELETE_IMAGE_FAILED",

    GET_STATISTICS_REQUEST: "GET_STATISTICS_REQUEST",
    GET_STATISTICS_SUCCESSFUL: "GET_STATISTICS_SUCCESSFUL",
    GET_STATISTICS_FAILED: "GET_STATISTICS_FAILED",

    GET_IMAGES_GALLERY_REQUEST: "GET_IMAGES_GALLERY_REQUEST",
    GET_IMAGES_GALLERY_SUCCESSFUL: "GET_IMAGES_GALLERY_SUCCESSFUL",
    GET_IMAGES_GALLERY_FAILED: "GET_IMAGES_GALLERY_FAILED"
};

export default constants;
